import { v4 as uuid } from "uuid";

export const products = [
  {
    category_name: "kid",
    description:
      "These premium leather sneakers embody urban sophistication with their sleek design, high-quality craftsmanship, and attention to detail.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393457/image-kids-1_yviesq.png",

    is_stock: false,
    liked: false,
    name: "Vanguard Elite",
    original_price: 12069,
    rating: 4.3,
    reviews: 109,
    size: 5,
    trending: true,
    _id: "ce24f6bd-2c9f-4e98-9fc7-5084759596f7",
  },
  {
    category_name: "kid",
    description:
      "These urban high-top sneakers feature a contemporary silhouette, luxurious materials, and impeccable stitching, making them a stylish choice for fashion-forward individuals.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393494/image-kids-2_z5xiyu.png",
    is_stock: true,
    liked: false,
    name: "Nova Pro X",
    original_price: 10569,
    rating: 4.1,
    reviews: 129,
    size: 7,
    trending: true,
    _id: "e1a88fe4-2aad-45a4-acc3-bd02ccb3f268",
  },
  {
    category_name: "kid",
    description:
      "Combining cutting-edge technology with urban style, these running shoes feature advanced cushioning, breathable mesh, and a sleek, streamlined design.",
    discounted_price: 6399,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393494/image-kids-3_lzzbon.png",
    is_stock: true,
    liked: false,
    name: "Ascend TechFit",
    original_price: 18019,
    rating: 2.7,
    reviews: 19,
    size: 4,
    trending: false,
    _id: "08bdb812-ff22-4e11-957d-1c615d80328c",
  },
  {
    category_name: "kid",
    description:
      "Made from supple, premium leather, these loafers exude elegance with their minimalist urban aesthetic and effortless slip-on design.",
    discounted_price: 18019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393494/image-kids-4_mgbp1v.png",
    is_stock: true,
    liked: false,
    name: "Velocity Prime",
    original_price: 28019,
    rating: 3.3,
    reviews: 10569,
    size: 9,
    trending: false,
    _id: "6e697154-a201-4f42-a2f7-97006f453a4d",
  },
  {
    category_name: "kid",
    description:
      "These urban boots are crafted from luxurious suede and boast a modern silhouette, making them a versatile and stylish choice for any occasion.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393494/image-kids-5_gbcypt.png",
    is_stock: true,
    liked: false,
    name: "Equinox Maxima",
    original_price: 38019,
    rating: 4.5,
    reviews: 109,
    size: 7,
    trending: false,
    _id: "915b7700-7ad8-4443-8c28-e7f9da5e7560",
  },
  {
    category_name: "kid",
    description:
      "Designed for the fashion-conscious urbanite, these sneakers feature bold colors, unique patterns, and premium materials, adding an eye-catching element to any outfit.",
    discounted_price: 7209,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393456/image-kids-6_c0kfdw.png",
    is_stock: true,
    liked: false,
    name: "Precision Optima",
    original_price: 8019,
    rating: 3.4,
    reviews: 39,
    size: 5,
    trending: false,
    _id: "186c93e7-3997-4a59-b56e-e6e9da91b501",
  },
  {
    category_name: "kid",
    description:
      "These premium leather Chelsea boots offer a perfect blend of urban style and timeless elegance, with their sleek silhouette and comfortable fit.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393527/image-kids-7_ckccbg.png",
    is_stock: true,
    liked: false,
    name: "Apex Fusion X",
    original_price: 38019,
    rating: 3.6,
    reviews: 32,
    size: 5,
    trending: false,
    _id: "9c473973-45ff-4878-9ff9-dcb9f46ff72b",
  },
  {
    category_name: "kid",
    description:
      "These urban slip-on sneakers combine fashion-forward design with premium materials, allowing for effortless style and comfort.",
    discounted_price: 48019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-kids-8_g0wzn3.png",
    is_stock: true,
    liked: false,
    name: "Quantum Impact",
    original_price: 58019,
    rating: 4.6,
    reviews: 1094,
    size: 7,
    trending: true,
    _id: "5033a44a-1e98-44b3-b81e-ba6ccf7fd339",
  },
  {
    category_name: "kid",
    description:
      "Urban Desert Boots: Made from high-quality materials, these desert boots feature a rugged yet refined urban look, making them an ideal choice for the modern adventurer.",
    discounted_price: 58019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-kids-9_ebgquz.png",
    is_stock: true,
    liked: false,
    name: "Elevation Ultra",
    original_price: 68019,
    rating: 4.5,
    reviews: 166,
    size: 7,
    trending: false,
    _id: "372584bf-e0e2-4e4e-9613-a5f71983b14d",
  },
  {
    category_name: "kid",
    description:
      "These urban leather sandals embody simplicity and sophistication, with their clean lines, premium materials, and understated elegance.",
    discounted_price: 78019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393495/image-kids-10_f6kbfx.png",
    is_stock: true,
    liked: false,
    name: "Radiant Elite",
    original_price: 88019,
    rating: 4.6,
    reviews: 47,
    size: 10,
    trending: false,
    _id: "d78ddbc5-babc-4f02-8a5a-03ad35cdbbb7",
  },
  {
    category_name: "kid",
    description:
      "These premium Oxford shoes feature a modern twist on a classic design, with urban-inspired details and impeccable craftsmanship.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393533/image-kids-11_youzox.png",
    is_stock: true,
    liked: false,
    name: "Ignite Pro X",
    original_price: 38019,
    rating: 3.3,
    reviews: 200,
    size: 9,
    trending: false,
    _id: "7a2d84ea-3fb7-4eea-985a-e96f3cd31da8",
  },
  {
    category_name: "kid",
    description:
      "Combining urban aesthetics with a touch of edginess, these platform sneakers boast premium materials, unique textures, and a comfortable lift.",
    discounted_price: 88019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393495/image-kids-12_h0wpby.png",
    is_stock: true,
    liked: false,
    name: "Luminary Evo",
    original_price: 80199,
    rating: 4,
    reviews: 222,
    size: 6,
    trending: false,
    _id: "fa097ba1-4c2a-4711-a15e-3fca6f412808",
  },
  {
    category_name: "kid",
    description:
      "These urban leather loafers offer a refined and polished look, with their premium construction, sleek silhouette, and exquisite detailing.",
    discounted_price: 58019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393496/image-kids-13_apyl3r.png",
    is_stock: false,
    liked: false,
    name: "Velocity Boost",
    original_price: 68019,
    rating: 3.1,
    reviews: 29,
    size: 6,
    trending: true,
    _id: "2666feb3-747e-4310-93da-c3e7ca3716d8",
  },
  {
    category_name: "kid",
    description:
      "These sneakers push the boundaries of urban footwear with their innovative materials, geometric patterns, and avant-garde design elements.",
    discounted_price: 88019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393496/image-kids-14_ltitck.png",
    is_stock: true,
    liked: false,
    name: "Synthesis Xcel",
    original_price: 80199,
    rating: 2.3,
    reviews: 25,
    size: 7,
    trending: false,
    _id: "02e7729f-4090-44a7-9f12-c4023d2e63b9",
  },
  {
    category_name: "kid",
    description:
      "These ankle boots feature a sleek urban silhouette, premium leather, and a statement zipper detail, adding a modern edge to any outfit.",
    discounted_price: 68019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393534/image-kids-15_hc2qk3.png",
    is_stock: false,
    liked: false,
    name: "Momentum Prime",
    original_price: 78019,
    rating: 1.7,
    reviews: 14,
    size: 8,
    trending: false,
    _id: "f492386b-9fe7-492b-8e19-06b07cb158e3",
  },
  {
    category_name: "kid",
    description:
      "These urban sneakers combine breathable knit fabric with premium accents, offering a modern and comfortable footwear option.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393535/image-kids-16_syyor1.png",
    is_stock: true,
    liked: false,
    name: "Optimum Stride",
    original_price: 38019,
    rating: 4.3,
    reviews: 144,
    size: 9,
    trending: false,
    _id: "49841381-3080-4fe5-bea1-016fe601df78",
  },
  {
    category_name: "kid",
    description:
      "These brogues feature a blend of classic charm and urban style, with their intricate perforations, luxurious leather, and urban-inspired finishes.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393535/image-kids-17_gdjydw.png",
    is_stock: false,
    liked: false,
    name: "Empower Pro X",
    original_price: 80199,
    rating: 4.2,
    reviews: 7209,
    size: 9,
    trending: true,
    _id: "2f15e542-7395-4238-bd36-30387ba41046",
  },
  {
    category_name: "kid",
    description:
      "Combining athletic functionality with urban aesthetics, these sneakers offer exceptional comfort, premium materials, and stylish design elements.",
    discounted_price: 118019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393496/image-kids-18_zuiqa5.png",
    is_stock: false,
    liked: false,
    name: "Elite Reactor",
    original_price: 128019,
    rating: 4.9,
    reviews: 398,
    size: 6,
    trending: false,
    _id: "8192d640-0880-470b-8e31-3fb199026998",
  },
  {
    category_name: "kid",
    description:
      "These premium leather sneakers embody urban sophistication with their sleek design, high-quality craftsmanship, and attention to detail.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393460/image-kids-19_gtdfdz.png",
    is_stock: false,
    liked: false,
    name: "Catalyst Hyper",
    original_price: 18019,
    rating: 4.7,
    reviews: 433,
    size: 5,
    trending: true,
    _id: "541c3933-6d75-49cd-98a0-a64115c5dc1a",
  },
  {
    category_name: "kid",
    description:
      "These derbies embody urban sophistication with their clean lines, premium leather, and a modern twist on a timeless silhouette.",
    discounted_price: 69,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-men-20_tzzf01.png",
    is_stock: true,
    liked: false,
    name: "Fusion Element",
    original_price: 6399,
    rating: 4.4,
    reviews: 19,
    size: 6,
    trending: false,
    _id: "63953420-71a9-4825-b394-b0ee6abf6477",
  },
  {
    category_name: "kid",
    description:
      "These urban joggers combine sporty design elements with luxurious materials, creating a unique and stylish footwear option for urban explorers.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-men-21_kykjgu.png",
    is_stock: false,
    liked: false,
    name: "Triumph Elite",
    original_price: 148019,
    rating: 4.3,
    reviews: 132,
    size: 7,
    trending: false,
    _id: "3968ed69-a6d7-4a6e-ad4f-0db4f210f88a",
  },
  {
    category_name: "men",
    description:
      "These ballet flats feature soft, premium leather, a refined urban silhouette, and a comfortable fit, offering a chic and versatile choice for urban dwellers.",
    discounted_price: 58019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393460/image-men-1_yngrkj.png",
    is_stock: true,
    liked: false,
    name: "Evolve Pro X",
    original_price: 68019,
    rating: 5,
    reviews: 132,
    size: 7,
    trending: true,
    _id: "6f89fedf-2e42-42fc-85c4-27b9ae724c6a",
  },
  {
    category_name: "men",
    description:
      "Crafted from plush suede, these sneakers exude urban luxury with their refined silhouette, attention to detail, and superior comfort.",
    discounted_price: 18019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393529/image-men-4_e3hrwy.png",
    is_stock: false,
    liked: false,
    name: "Innovate Optima",
    original_price: 28019,
    rating: 4.8,
    reviews: 654,
    size: 8,
    trending: true,
    _id: "f0b37411-f423-45a1-9b96-db695c6b9c36",
  },
  {
    category_name: "men",
    description:
      "Designed for urban explorers, these hiking boots feature a durable construction, rugged tread, and urban-inspired accents, ensuring both style and functionality.",
    discounted_price: 38019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393529/image-men-5_lj58xj.png",
    is_stock: true,
    liked: false,
    name: "Phoenix Fusion",
    original_price: 48019,
    rating: 3.9,
    reviews: 65,
    size: 9,
    trending: false,
    _id: "bf4f1437-100a-4ca2-b69e-5634e037d9d1",
  },
  {
    category_name: "men",
    description:
      "These monk strap shoes redefine urban sophistication with their premium leather, sleek buckle closure, and contemporary silhouette.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393459/image-men-6_vsp03o.png",
    is_stock: true,
    liked: false,
    name: "Turbo Impact",
    original_price: 148019,
    rating: 3.5,
    reviews: 43,
    size: 7,
    trending: false,
    _id: "6b6e8030-f2df-4d3b-865a-1ea99f0b8817",
  },
  {
    category_name: "men",
    description:
      "These sandals combine urban style with warm-weather comfort, featuring a cushioned footbed, premium materials, and a trendy streetwear-inspired design.",
    discounted_price: 88019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393530/image-men-7_sxqeeb.png",
    is_stock: false,
    liked: false,
    name: "Aether Ultra",
    original_price: 80199,
    rating: 2.5,
    reviews: 8019,
    size: 5,
    trending: true,
    _id: "20fef86c-9fa2-45b0-aefa-68b51d26b58b",
  },
  {
    category_name: "men",
    description:
      "Perfect for summer, these slip-on espadrilles showcase an urban twist with their premium materials, jute-wrapped sole, and effortless style.",
    discounted_price: 18019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393535/image-men-8_scpoae.png",
    is_stock: false,
    liked: false,
    name: "Precision Glide",
    original_price: 28019,
    rating: 4.9,
    reviews: 1809,
    size: 6,
    trending: true,
    _id: "f15f7898-683f-4c1f-9048-e62c43f1da21",
  },
  {
    category_name: "men",
    description:
      "Blurring the lines between sneakers and boots, these hybrid shoes feature a sleek urban design, premium materials, and a comfortable fit.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393535/image-men-9_cclciw.png",
    is_stock: true,
    liked: false,
    name: "Luminous Elite",
    original_price: 38019,
    rating: 4,
    reviews: 65,
    size: 5,
    trending: false,
    _id: "0d053cc8-901e-4b56-b3f3-19b63b43859f",
  },
  {
    category_name: "men",
    description:
      "These Chelsea sneakers offer a unique blend of urban style and sporty appeal, featuring a slip-on design, premium materials, and a contemporary silhouette.",
    discounted_price: 48019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393455/image-men-10_biwtds.png",
    is_stock: true,
    liked: false,
    name: "Surge Pro X",
    original_price: 58019,
    rating: 4.8,
    reviews: 78,
    size: 12,
    trending: false,
    _id: "a1a7d56e-5ece-41a6-b8e1-e336d9c77eb8",
  },
  {
    category_name: "men",
    description:
      "These wingtip shoes exude urban elegance with their detailed broguing, premium leather, and a modern interpretation of a classic design.",
    discounted_price: 138019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393527/image-men-11_samgvs.png",
    is_stock: true,
    liked: false,
    name: "Quantum Evo",
    original_price: 148019,
    rating: 5,
    reviews: 45,
    size: 11,
    trending: false,
    _id: "b58788b5-1134-4f8d-a1f9-9a8c7c2922b8",
  },
  {
    category_name: "men",
    description:
      "Combining sporty functionality with urban aesthetics, these sandals feature adjustable straps, cushioned footbeds, and a sleek design, perfect for on-the-go comfort.",
    discounted_price: 68019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393527/image-men-12_jtuhxn.png",
    is_stock: true,
    liked: false,
    name: "Momentum Boost",
    original_price: 78019,
    rating: 3.5,
    reviews: 123,
    size: 10,
    trending: false,
    _id: "9ee4d26b-a309-46b8-acaa-0e1085d92e3c",
  },
  {
    category_name: "men",
    description:
      "These low-top sneakers showcase a minimalist urban aesthetic with their clean lines, premium materials, and versatile color options.",
    discounted_price: 108019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393527/image-men-13_qkof6z.png",
    is_stock: true,
    liked: false,
    name: "Harmony Xcel",
    original_price: 118019,
    rating: 4.2,
    reviews: 987,
    size: 9,
    trending: false,
    _id: "66f2db4f-68e6-45de-af2e-7c31d8fe6b6f",
  },
  {
    category_name: "men",
    description:
      "These derby boots offer a contemporary twist on a classic silhouette, combining premium leather, urban-inspired details, and a comfortable fit.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393528/image-men-14_hm5zrm.png",
    is_stock: true,
    liked: false,
    name: "Propel Prime",
    original_price: 38019,
    rating: 4.3,
    reviews: 654,
    size: 8,
    trending: false,
    _id: "e0d15ba4-cfb8-49c7-bba7-90af181f6ba1",
  },
  {
    category_name: "men",
    description:
      "These lightweight slip-on shoes feature a breathable knit upper, flexible sole, and a modern urban design, providing comfort and style for everyday wear.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393528/image-men-15_ibobk7.png",
    is_stock: false,
    liked: false,
    name: "Dynamo Stride",
    original_price: 18019,
    rating: 4.3,
    reviews: 7209,
    size: 9,
    trending: true,
    _id: "499cbb8f-c6c0-4802-b5b2-8f5c05212737",
  },
  {
    category_name: "men",
    description:
      "These penny loafers exude urban sophistication with their polished leather, refined silhouette, and timeless style, suitable for both casual and formal occasions.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393528/image-men-16_plunul.png",
    is_stock: false,
    liked: false,
    name: "Enigma Pro X",
    original_price: 108019,
    rating: 4.6,
    reviews: 43,
    size: 8,
    trending: true,
    _id: "7b6bd9b1-ea8a-4cf7-8cdb-8a463f009bf9",
  },
  {
    category_name: "men",
    description:
      "These sneaker wedges combine urban chic with added height, featuring a concealed wedge heel, premium materials, and a fashion-forward design.",
    discounted_price: 158019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393456/image-men-17_ajiahs.png",
    is_stock: true,
    liked: false,
    name: "Zenith Reactor",
    original_price: 168019,
    rating: 4.7,
    reviews: 76,
    size: 6,
    trending: true,
    _id: "bba7d5dd-0795-4106-986d-db8da0f85e53",
  },
  {
    category_name: "men",
    description:
      "Inspired by desert footwear, these sandals feature a blend of urban style and comfort, with premium materials, adjustable straps, and a cushioned footbed.",
    discounted_price: 158019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393499/image-men-18_tffjvx.png",
    is_stock: true,
    liked: false,
    name: "Catalyst Hyperion",
    original_price: 168019,
    rating: 4.8,
    reviews: 7209,
    size: 8,
    trending: false,
    _id: "7fa2f881-9da4-4d4a-9fe4-f9dd9f928ce5",
  },
  {
    category_name: "men",
    description:
      "Blending the elegance of oxford shoes with the comfort of sneakers, these urban sneakers offer a sleek design, premium materials, and versatile styling options.",
    discounted_price: 168019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393467/image-men-19_n9sseo.png",
    is_stock: true,
    liked: false,
    name: "Fusion Prodigy",
    original_price: 178019,
    rating: 1.2,
    reviews: 78,
    size: 9,
    trending: true,
    _id: "69b9bef7-cde6-45cf-ba9d-00c5d8650770",
  },
  {
    category_name: "men",
    description:
      "These boat shoes boast an urban twist with their slip-on design, premium leather, and a non-slip sole, offering both style and functionality.",
    discounted_price: 178019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393499/image-men-20_gelxtj.png",
    is_stock: true,
    liked: false,
    name: "Vanguard Accelerate",
    original_price: 188019,
    rating: 1.6,
    reviews: 43,
    size: 10,
    trending: false,
    _id: "83873bb7-9299-43f8-bbf7-6ba3c927642d",
  },
  {
    category_name: "men",
    description:
      "These slip-on mules offer an effortless urban style with their premium materials, backless design, and a comfortable yet sophisticated look.",
    discounted_price: 138019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-men-21_kykjgu.png",
    is_stock: true,
    liked: false,
    name: "Nova Ignition",
    original_price: 148019,
    rating: 2.6,
    reviews: 54,
    size: 9,
    trending: false,
    _id: "dc2fc7e3-8a3a-4afd-afd6-1ef09b3b6d17",
  },
  {
    category_name: "men",
    description:
      "These wingtip boots combine urban edge with classic details, featuring premium leather, brogue accents, and a sturdy construction for all-day comfort.",
    discounted_price: 188019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-22_ohmduh.png",
    is_stock: true,
    liked: false,
    name: "Ascend Velocity",
    original_price: 180199,
    rating: 2.4,
    reviews: 9,
    size: 6,
    trending: true,
    _id: "da9df633-f82b-4c7a-915e-9a5de8bb1033",
  },
  {
    category_name: "men",
    description:
      "These sock-style sneakers redefine urban footwear with their sleek silhouette, stretch-knit fabric, and contemporary design elements.",
    discounted_price: 180199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-23_mseede.png",
    is_stock: true,
    liked: false,
    name: "Velocity Quantum",
    original_price: 208019,
    rating: 4.9,
    reviews: 555,
    size: 8,
    trending: false,
    _id: "4ebab1fc-58ca-4b0d-98b1-87b156bfeaaf",
  },
  {
    category_name: "men",
    description:
      "These platform sneakers make a bold urban statement with their chunky sole, premium materials, and a fashion-forward design that stands out from the crowd.",
    discounted_price: 208019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-24_md8dfo.png",
    is_stock: true,
    liked: false,
    name: "Equinox Dynamo",
    original_price: 218019,
    rating: 4.8,
    reviews: 325,
    size: 5,
    trending: false,
    _id: "75b9781c-6abf-4ee6-aff4-190a3b9f3cc5",
  },
  {
    category_name: "men",
    description:
      "These slingback flats offer a modern urban twist with their sleek silhouette, premium materials, and a comfortable yet chic design that pairs well with any outfit.",
    discounted_price: 128019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393536/image-men-25_wfofst.png",
    is_stock: false,
    liked: false,
    name: "Precision Apex",
    original_price: 138019,
    rating: 4.6,
    reviews: 986,
    size: 5,
    trending: true,
    _id: "f23e4b25-a125-4837-816a-92804f1653e0",
  },
  {
    category_name: "men",
    description:
      "These chukka boots feature urban-inspired details, such as premium leather, contrasting stitching, and a versatile design suitable for both casual and dressier occasions.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-26_gav9nw.png",
    is_stock: false,
    liked: false,
    name: "Apex Quantum X",
    original_price: 118019,
    rating: 3.2,
    reviews: 777,
    size: 7,
    trending: false,
    _id: "65e5b988-af13-450e-bfee-5db97414d601",
  },
  {
    category_name: "men",
    description:
      "These slip-on sandals combine urban flair with warm-weather comfort, featuring premium materials, a cushioned footbed, and a minimalist yet stylish design.",
    discounted_price: 138019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-27_zooy8v.png",
    is_stock: true,
    liked: false,
    name: "Quantum Velocity",
    original_price: 148019,
    rating: 3.8,
    reviews: 432,
    size: 8,
    trending: true,
    _id: "e7782da7-746d-4a9d-8c80-10913a3564e7",
  },
  {
    category_name: "men",
    description:
      "These wedge ankle boots elevate your urban style with their sleek silhouette, premium materials, and a comfortable wedge heel that adds height and sophistication.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393529/image-men-28_swsell.png",
    is_stock: true,
    liked: false,
    name: "Elevation Dynamo X",
    original_price: 108019,
    rating: 3.7,
    reviews: 457,
    size: 9,
    trending: false,
    _id: "47d903a3-8020-4dd5-bef9-353856e69d13",
  },
  {
    category_name: "men",
    description:
      "These sneaker booties fuse urban edge with a sporty vibe, featuring a high-top silhouette, premium materials, and bold design elements for a standout look.",
    discounted_price: 88019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393528/image-men-29_prja4e.png",
    is_stock: true,
    liked: false,
    name: "Radiant Momentum",
    original_price: 80199,
    rating: 3.4,
    reviews: 34,
    size: 10,
    trending: false,
    _id: "fb9486c7-2fc3-40c4-8472-68a71138b818",
  },
  {
    category_name: "men",
    description:
      "These driving moccasins offer a refined urban style with their premium leather, comfortable fit, and a versatile design suitable for both casual and dressier occasions.",
    discounted_price: 58019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-30_ounfbw.png",
    is_stock: true,
    liked: false,
    name: "Ignite Precision",
    original_price: 78019,
    rating: 5,
    reviews: 976,
    size: 12,
    trending: false,
    _id: "ba470bc9-0bee-4b97-abe4-bbf0208fcb10",
  },
  {
    category_name: "men",
    description:
      "These slip-on loafers embody simplicity and urban sophistication, featuring clean lines, premium materials, and a sleek design that effortlessly elevates any outfit.",
    discounted_price: 58019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393502/image-men-31_vxocye.png",
    is_stock: true,
    liked: false,
    name: "Luminary Synthesis",
    original_price: 68019,
    rating: 4.8,
    reviews: 322,
    size: 11,
    trending: false,
    _id: "d807059d-6d16-4b62-986d-ea69215c0f9d",
  },
  {
    category_name: "men",
    description:
      "These platform sandals exude urban chic with their elevated sole, premium materials, and a trendy design that adds a fashionable touch to your summer wardrobe.",
    discounted_price: 38019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393537/image-men-32_uxwawq.png",
    is_stock: false,
    liked: false,
    name: "Velocity Momentum X",
    original_price: 48019,
    rating: 4.5,
    reviews: 56,
    size: 10,
    trending: false,
    _id: "43e4a88c-d529-41fc-998d-666371938135",
  },
  {
    category_name: "men",
    description:
      "These Chelsea sneakers blend urban style with athletic elements, featuring premium leather, elastic side panels, and a sporty yet sophisticated design.",
    discounted_price: 7209,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393538/image-men-34_kb7mic.png",
    is_stock: false,
    liked: false,
    name: "Synthesis Optimum",
    original_price: 8019,
    rating: 4.1,
    reviews: 345,
    size: 9,
    trending: false,
    _id: "aaeffaeb-092b-4e41-ab48-9511fdaa3f97",
  },
  {
    category_name: "women",
    description:
      "These suede driving shoes combine urban sophistication with a touch of casual style, featuring premium suede, comfortable fit, and a versatile design.",
    discounted_price: 48019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393462/image-women-1_vjjhgv.png",
    is_stock: true,
    liked: false,
    name: "Optimum Elite",
    original_price: 58019,
    rating: 4.8,
    reviews: 1609,
    size: 5,
    trending: false,
    _id: "aace9c14-32c5-4542-bee8-55c2e9d96769",
  },
  {
    category_name: "women",
    description:
      "These high-top sneakers showcase a modern urban aesthetic with their breathable knit fabric, premium materials, and a streetwear-inspired design that stands out.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393535/image-women-2_afilsl.png",
    is_stock: true,
    liked: false,
    name: "Empower Catalyst",
    original_price: 12069,
    rating: 4.3,
    reviews: 109,
    size: 5,
    trending: false,
    _id: "adfec418-1d66-490b-82b1-350a5f840158",
  },
  {
    category_name: "women",
    description:
      "These gladiator sandals offer a bold urban look with their premium leather construction, multiple straps, and a stylish lace-up design that adds a trendy edge to your outfit.",
    discounted_price: 118019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393533/image-women-4_wgqgoe.png",
    is_stock: true,
    liked: false,
    name: "Catalyst Apex X",
    original_price: 128019,
    rating: 4.9,
    reviews: 65,
    size: 7,
    trending: false,
    _id: "34e37246-cd08-4854-9a78-126b10515ead",
  },
  {
    category_name: "women",
    description:
      "These slip-on oxfords combine urban sophistication with ease of wear, featuring premium leather, a sleek silhouette, and a convenient slip-on design for a polished yet effortless look.",
    discounted_price: 168019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393503/image-women-5_neh8eb.png",
    is_stock: true,
    liked: false,
    name: "Fusion Quantum",
    original_price: 178019,
    rating: 4.6,
    reviews: 765,
    size: 8,
    trending: false,
    _id: "c9b2b9a6-43e1-46ed-bb30-4a9c42611f22",
  },
  {
    category_name: "women",
    description:
      "These platform oxford shoes elevate your urban style with their chunky sole, premium materials, and a contemporary design that adds height and fashion-forward appeal.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393533/image-women-6_qefx7c.png",
    is_stock: true,
    liked: false,
    name: "Triumph Ignite",
    original_price: 108019,
    rating: 4.7,
    reviews: 45,
    size: 5,
    trending: false,
    _id: "1593365f-d427-4455-9ea5-f38859035998",
  },
  {
    category_name: "women",
    description:
      "These suede sneaker boots blend the versatility of sneakers with the warmth and style of boots, featuring premium suede, a mid-top silhouette, and a trendy urban design.",
    discounted_price: 7209,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393504/image-women-7_dwadx9.png",
    is_stock: true,
    liked: false,
    name: "Evolve Luminary",
    original_price: 8019,
    rating: 4.8,
    reviews: 8019,
    size: 5,
    trending: false,
    _id: "7229d284-57cc-49be-b0db-ad9515a17357",
  },
  {
    category_name: "women",
    description:
      "These moccasin sneakers combine the comfort of moccasins with the urban style of sneakers, featuring premium leather, a sporty silhouette, and a versatile design suitable for various occasions.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393532/image-women-9_iqohlw.png",
    is_stock: false,
    liked: false,
    name: "Accelerate Equinox",
    original_price: 148019,
    rating: 4.9,
    reviews: 543,
    size: 8,
    trending: false,
    _id: "9c8bcea6-a01c-4016-b19c-18a03a2b364e",
  },
  {
    category_name: "women",
    description:
      " These T-strap sandals showcase a modern urban aesthetic with their premium materials, adjustable straps, and a stylish design that adds a touch of sophistication to your warm-weather looks.",
    discounted_price: 148019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393503/image-women-10_zkbo8y.png",
    is_stock: false,
    liked: false,
    name: "Innovate Precision X",
    original_price: 158019,
    rating: 3,
    reviews: 78,
    size: 11,
    trending: true,
    _id: "12e45d09-497d-452c-9edc-69cace88230a",
  },
  {
    category_name: "women",
    description:
      "These Chelsea boots exude urban coolness with their premium leather, studded accents, and a sleek silhouette that effortlessly blends style and attitude.",
    discounted_price: 128019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393504/image-women-11_tbjyng.png",
    is_stock: true,
    liked: false,
    name: "Phoenix Apex",
    original_price: 138019,
    rating: 3.3,
    reviews: 5,
    size: 12,
    trending: false,
    _id: "f72d9253-2a15-4287-8d15-2423678fecc1",
  },
  {
    category_name: "women",
    description:
      "These slip-on sneaker mules offer a chic and effortless urban style with their premium materials, backless design, and a modern twist on a classic sneaker look.",
    discounted_price: 108019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393532/image-women-12_reeqww.png",
    is_stock: true,
    liked: false,
    name: "Turbo Quantum X",
    original_price: 118019,
    rating: 3.4,
    reviews: 11,
    size: 9,
    trending: false,
    _id: "dc9373ff-69fb-4e80-a03a-1583a1bbd261",
  },
  {
    category_name: "women",
    description:
      "These slingback pumps elevate your urban elegance with their premium leather, sleek silhouette, and a comfortable heel height that adds sophistication to your outfits.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393531/image-women-13_zvtmdz.png",
    is_stock: true,
    liked: false,
    name: "Aether Elevation",
    original_price: 108019,
    rating: 4.5,
    reviews: 22,
    size: 7,
    trending: false,
    _id: "49e6dc55-8856-4a90-8843-b41f96e8e987",
  },
  {
    category_name: "women",
    description:
      "These sneaker boots combine the ruggedness of hiking boots with the urban appeal of sneakers, featuring durable materials, a grippy outsole, and a sporty design perfect for urban adventures.",
    discounted_price: 38019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393530/image-women-14_kyhdka.png",
    is_stock: true,
    liked: false,
    name: "Precision Surge",
    original_price: 48019,
    rating: 4.2,
    reviews: 97,
    size: 5,
    trending: false,
    _id: "50c92972-0b21-43c8-aeb4-06a1695fc3e4",
  },
  {
    category_name: "women",
    description:
      "These slide sandals embody minimalist urban style with their premium leather, clean lines, and a simple yet refined design that effortlessly complements any outfit.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393529/image-women-15_afrpri.png",
    is_stock: false,
    liked: false,
    name: "Luminous Momentum X",
    original_price: 38019,
    rating: 4.3,
    reviews: 245,
    size: 7,
    trending: true,
    _id: "b1c6ffc1-c0ec-49d6-950c-b0b768dfb673",
  },
  {
    category_name: "women",
    description:
      "These wedge sneakers add a touch of urban glamour with their metallic accents, premium materials, and a comfortable wedge heel that adds height and style.",
    discounted_price: 18019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393530/image-women-16_iqb0ph.png",
    is_stock: true,
    liked: false,
    name: "Surge Optimum",
    original_price: 28019,
    rating: 2.9,
    reviews: 43,
    size: 10,
    trending: true,
    _id: "cffcf661-8e8a-4d55-89d5-caa11dc6c834",
  },
  {
    category_name: "women",
    description:
      "These moto boots exude urban edge with their rugged leather construction, buckle accents, and a sturdy design that combines style with durability.",
    discounted_price: 180199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393536/image-women-18_ahsgzh.png",
    is_stock: true,
    liked: false,
    name: "Momentum Elite",
    original_price: 208019,
    rating: 3.3,
    reviews: 8019,
    size: 8,
    trending: false,
    _id: "9a409ab6-0f66-45f0-aab2-0bd3219c72b3",
  },
  {
    category_name: "women",
    description:
      "These cutout booties offer a trendy urban look with their unique design, premium materials, and a modern silhouette that adds a fashionable touch to your footwear collection.",
    discounted_price: 138019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393505/image-women-19_aancj2.png",
    is_stock: true,
    liked: false,
    name: "Harmony Catalyst",
    original_price: 148019,
    rating: 1.4,
    reviews: 109,
    size: 7,
    trending: false,
    _id: "548e01c0-c5d1-4af0-9c00-7650f685bf2b",
  },
  {
    category_name: "women",
    description:
      "These Oxford flats offer a stylish urban twist with their premium materials, lace-up closure, and a sleek silhouette that adds a touch of sophistication to any outfit.",
    discounted_price: 188019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393462/image-women-22_a1j6ij.png",
    is_stock: false,
    liked: false,
    name: "Enigma Nova X",
    original_price: 178019,
    rating: 4.3,
    reviews: 2133,
    size: 11,
    trending: false,
    _id: "57b81d85-761e-47e4-b1eb-5219d1cf54d9",
  },
  {
    category_name: "women",
    description:
      "These sock booties showcase a modern urban aesthetic with their stretchy knit fabric, snug fit, and a sleek design that hugs your ankles for a trendy and comfortable look.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393505/image-women-23_u3hbuf.png",
    is_stock: true,
    liked: false,
    name: "Zenith Ascend",
    original_price: 159,
    rating: 3.5,
    reviews: 34,
    size: 12,
    trending: false,
    _id: "62e4fb33-1ef2-4fcb-af43-bcdc9a1a8ba3",
  },
  {
    category_name: "women",
    description:
      "These tassel loafers exude urban charm with their premium leather, classic silhouette, and stylish tassel detailing, making them a versatile choice for both casual and formal occasions.",
    discounted_price: 8019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393466/image-women-24_p6u0hf.png",
    is_stock: true,
    liked: false,
    name: "Catalyst Velocity X",
    original_price: 18019,
    rating: 3.4,
    reviews: 67209,
    size: 11,
    trending: true,
    _id: "43fcb156-fae1-40ad-8a30-d41694177b2a",
  },
  {
    category_name: "women",
    description:
      "These platform sandals elevate your urban style with their chunky sole, premium materials, and a trendy design that adds height and fashion-forward flair to your summer wardrobe.",
    discounted_price: 118019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393505/image-women-25_yl6irj.png",
    is_stock: true,
    liked: false,
    name: "Fusion Equinox",
    original_price: 128019,
    rating: 4,
    reviews: 36,
    size: 10,
    trending: false,
    _id: "fd731dd2-7005-4f5d-bf9a-3770193edf2a",
  },
  {
    category_name: "women",
    description:
      "These studded sneakers offer an edgy urban vibe with their premium materials, metallic stud accents, and a unique design that adds a rebellious touch to your footwear collection.",
    discounted_price: 80199,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393534/image-women-26_nuegk2.png",
    is_stock: true,
    liked: false,
    name: "Vanguard Precision",
    original_price: 108019,
    rating: 4.1,
    reviews: 67,
    size: 9,
    trending: false,
    _id: "88e45d47-115a-4125-84df-f0fcde379540",
  },
  {
    category_name: "women",
    description:
      "These lace-up booties combine urban chic with a touch of ruggedness, featuring premium leather, a stacked heel, and a versatile design that pairs well with various outfits.",
    discounted_price: 178019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393534/image-women-27_rebam6.png",
    is_stock: true,
    liked: false,
    name: "Nova Apex X",
    original_price: 188019,
    rating: 4.2,
    reviews: 67,
    size: 9,
    trending: false,
    _id: "ba838174-a889-4890-9842-79b2699922f0",
  },
  {
    category_name: "women",
    description:
      "These suede espadrilles showcase a modern urban aesthetic with their premium materials, jute-wrapped sole, and a stylish design that effortlessly blends comfort and style.",
    discounted_price: 158019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393458/image-women-28_cy4edd.png",
    is_stock: true,
    liked: false,
    name: "Ascend Quantum",
    original_price: 168019,
    rating: 4.3,
    reviews: 109,
    size: 6,
    trending: true,
    _id: "ccb0ac05-39c5-4f10-a25f-9d322e4a35aa",
  },
  {
    category_name: "women",
    description:
      "These chunky heel mules offer an urban flair with their premium materials, comfortable block heel, and a contemporary design that adds a trendy touch to your footwear collection.",
    discounted_price: 78019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393506/image-women-29_xjefdl.png",
    is_stock: true,
    liked: false,
    name: "Velocity Triumph",
    original_price: 88019,
    rating: 4.7,
    reviews: 235,
    size: 8,
    trending: true,
    _id: "3a8c654f-417e-45c5-83d1-f90b0079d653",
  },
  {
    category_name: "women",
    description:
      "These ballet flats exude urban sophistication with their premium leather, refined silhouette, and a timeless design that complements both casual and dressier looks.",
    discounted_price: 48019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393506/image-women-30_k5uoco.png",
    is_stock: false,
    liked: false,
    name: "Equinox Evolve",
    original_price: 58019,
    rating: 3.7,
    reviews: 543,
    size: 11,
    trending: true,
    _id: "a603b6d3-9f6e-47f0-be14-82e8d5976fdf",
  },
  {
    category_name: "women",
    description:
      "These slip-on sneaker boots combine the ease of slip-on shoes with the style of boots, featuring premium materials, a mid-top silhouette, and a fashion-forward design that effortlessly elevates your urban outfits.",
    discounted_price: 28019,
    img: "https://res.cloudinary.com/dnv5dhp9h/image/upload/v1688393507/image-women-31_qq9ojq.png",
    is_stock: true,
    liked: false,
    name: "Precision Stellar X",
    original_price: 38019,
    rating: 3.5,
    reviews: 69,
    size: 8,
    trending: false,
    _id: "afae1781-d59a-48a6-8a70-5953ae356303",
  },
];
